services:
  database:
    image: postgres:18.1-alpine3.23
    restart: always
    shm_size: 128mb
    volumes:
      - ./migrations/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DATABASE: postrun
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
